[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app"
PORT = "8080"
WHATSAPP_PORT = "3001"
WHATSAPP_URL = "http://127.0.0.1:3001"